services:
  tarantool:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.db
    ports:
      - "3301:3301"
    networks:
      - app_net

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - tarantool
    networks:
      - app_net

networks:
  app_net:
    driver: bridge